pangenome_samples:
  A: 'asm5'
  B: 'asm20'
  C: 'asm10'

additional_samples:
  - D
  - E


## minigraph bubble size
minigraph:
  L: 50
  divergence: 0.02

pggb:
  divergence: 98
  segment_length: 100000
  container: ~

cactus:
  container: ~

## vcf deconstruction
skip_size: 1000000

TR_divergence_limit: 0.25
timeout: 150

repeat_library: 'repeats.fasta'

optical_map_URL: 'https://zenodo.org/record/6854879/files/Merged_minQ20_maxDist1000.vcf.gz'

graphaligner_parameters:
  window: 500000
  strict: '-x vg'
  lenient: '-x dbg -C 1000000 --max-trace-count 5  --precise-clipping 0.9 --seeds-minimizer-ignore-frequent 0.001'

intersection_parameters:
  strict: 'max_dist=10 max_dist_linear=.5 min_seq_id=0.5'
  stricter: 'max_dist=5 max_dist_linear=.1 min_seq_id=0.5'
  strictest: 'max_dist=1 max_dist_linear=0 min_seq_id=0.85'
  lenient: 'max_dist_linear=0.5 max_dist=1000'
  lenientest: 'max_dist_linear=1 max_dist=10000'
  optical: 'max_dist_linear=1'
